import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Sidebar from "@/components/Sidebar";
import WholeContext from "./WholeContext";
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HobbyTube | Find your interests",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" >   
      <body className={inter.className}> 
      <WholeContext>
        <Navbar/>
        <Sidebar/>
        {children}
      </WholeContext>
      </body>
    </html>
    </ClerkProvider>
  );
}
